services:

  nextjs:
    build: .
    container_name: nextjs_app
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    depends_on:
      - nextjs
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
