  const carBrandsData = [
    "Alfa Romeo",
    "Audi, BMW",
    "Chevrolet",
    "Chrysler",
    "Dodge",
    "Ferrari",
    "Ford",
    "Hummer",
    "Lincoln",
    "Maybach",
    "Mazda",
    "Mercedes",
    "Opel",
    "Peugeot",
    "Porsche",
    "Renault",
    "Skoda",
    "Volkswagen",
  ];
